### ISSUE TITLE
Getting file.pipe is not a function error

### ISSUE THREAD

**Issue by durga73** [terrierscript/gulp-unzip#24]
When I am trying to unzip as 
  src("./src/lib/xxxxxxxxxx.zip ")
        .pipe(unzip())
        .pipe(dest('./src/lib/'));

I am getting the below error

    file.pipe(unzip.Parse())
         ^

TypeError: file.pipe is not a function
    at DestroyableTransform.transform [as _transform] (/Applications/apache-tomcat-7.0.93/webapps/node_modules/gulp-unzip/index.js:17:10)
    at DestroyableTransform.Transform._read (/Applications/apache-tomcat-7.0.93/webapps/node_modules/gulp-unzip/node_modules/readable-stream/lib/_stream_transform.js:177:10)
    at DestroyableTransform.Transform._write (/Applications/apache-tomcat-7.0.93/webapps/node_modules/gulp-unzip/node_modules/readable-stream/lib/_stream_transform.js:164:83)
    at doWrite (/Applications/apache-tomcat-7.0.93/webapps/node_modules/gulp-unzip/node_modules/readable-stream/lib/_stream_writable.js:405:139)
    at writeOrBuffer (/Applications/apache-tomcat-7.0.93/webapps/node_modules/gulp-unzip/node_modules/readable-stream/lib/_stream_writable.js:394:5)
    at DestroyableTransform.Writable.write (/Applications/apache-tomcat-7.0.93/webapps/node_modules/gulp-unzip/node_modules/readable-stream/lib/_stream_writable.js:303:11)
    at DestroyableTransform.ondata (/Applications/apache-tomcat-7.0.93/webapps/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:619:20)
    at DestroyableTransform.emit (events.js:197:13)
    at DestroyableTransform.EventEmitter.emit (domain.js:504:23)
    at addChunk (/Applications/apache-tomcat-7.0.93/webapps/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:291:12)
    at readableAddChunk (/Applications/apache-tomcat-7.0.93/webapps/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:278:11)
    at DestroyableTransform.Readable.push (/Applications/apache-tomcat-7.0.93/webapps/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:245:10)
    at DestroyableTransform.Transform.push (/Applications/apache-tomcat-7.0.93/webapps/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:148:32)
    at Pumpify.onReadable (/Applications/apache-tomcat-7.0.93/webapps/node_modules/to-through/index.js:25:14)
    at Pumpify.emit (events.js:197:13)
    at Pumpify.EventEmitter.emit (domain.js:504:23)

Here are gulp version

gulp --version
CLI version 2.1.0
Local version 4.0.0

**Comment by hmuronaka** [comment]
I have same problem, after updating gulp4 from gulp3.9.1

**Comment by terrierscript** [comment]
cc @UlisesGascon

**Comment by UlisesGascon** [comment]
Hi @durga73! Thanks for report it. 
We are working for support Gulp@4, #1. Right now we only support Gulp@3, I will ping you as soon is ready ;-)

**Comment by tgriley** [comment]
Any news on an ETA?

**Comment by UlisesGascon** [comment]
Hi @tgriley. I will create a PR in few minutes ;-)

**Comment by UlisesGascon** [comment]
@durga73 this is now fix. Use latest version (1.1.0). `npm uninstall gulp-unzip --save && npm install gulp-unzip --save`
